// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back_end.Contexts;

#nullable disable

namespace back_end.Migrations
{
    [DbContext(typeof(ChatApplicationDb))]
    [Migration("20230816090629_init1")]
    partial class init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("back_end.Entities.Account", b =>
                {
                    b.Property<int>("account_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("account_id"));

                    b.Property<int?>("ChatBoxchat_box_id")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("account_id");

                    b.HasIndex("ChatBoxchat_box_id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("back_end.Entities.ChatBox", b =>
                {
                    b.Property<int>("chat_box_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("chat_box_id"));

                    b.Property<int>("room")
                        .HasColumnType("integer");

                    b.HasKey("chat_box_id");

                    b.ToTable("ChatBoxes");
                });

            modelBuilder.Entity("back_end.Entities.Account", b =>
                {
                    b.HasOne("back_end.Entities.ChatBox", null)
                        .WithMany("accounts")
                        .HasForeignKey("ChatBoxchat_box_id");
                });

            modelBuilder.Entity("back_end.Entities.ChatBox", b =>
                {
                    b.Navigation("accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
